[metadata]
name = basicpkg
version = 1.0.0
author = Md Hanif Ali Sohag
author_email = hanifalisohag@gmail.com
description = A simple Python package
long_description = file: README.md, LICENSE.txt
long_description_content_type = text/markdown
url = https://github.com/hanifalisohag/basicpkg
license = MIT
project_urls =
    Bug Tracker = https://github.com/hanifalisohag/basicpkg/-/issues
    repository = https://github.com/hanifalisohag/basicpkg
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.6
install_requires =
    # Add dependencies here
[options.packages.find]
where = src